# Generated by Django 4.1 on 2023-10-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chromeapp', '0002_alter_customuser_fromchrome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fromchrome',
            field=models.BooleanField(null=True),
        ),
    ]
