# Generated by Django 4.1 on 2023-10-04 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chromeapp', '0004_album'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Album',
            new_name='Todo',
        ),
    ]
