# Generated by Django 4.1 on 2023-10-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chromeapp', '0005_rename_album_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='duedate',
            field=models.DateTimeField(),
        ),
    ]
