# Generated by Django 4.1 on 2023-10-10 17:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chromeapp', '0008_websitemonitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitemonitor',
            name='viewed_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
